data_version: S1
arch_name: LinkNet
encoder_name: efficientnet-b4
encoder_weights: imagenet
vv2rgb_name: fft
model_version: default
hparams:
  -
    image_size: 640
    learning_rate: 0.0001
    max_epochs: 300
    batch_size: 4
    accumulate_grad_batches: 1