data_version: S1
arch_name: MAnet
encoder_name: timm-gernet_s
encoder_weights: imagenet
vv2rgb_name: slog
model_version: default
hparams:
  -
    image_size: 640
    learning_rate: 0.001
    max_epochs: 200
    batch_size: 16
    accumulate_grad_batches: 1