name: oilspills
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - torchaudio
  - torchvision
  - conda-forge::segmentation-models-pytorch
  - gdal
  - albumentations
  - lightning
  - ipykernel
  - matplotlib
  - pandas
  - conda-forge::tensorboard
  - conda-forge::tensorboardx
  - pyyaml