data_version: S1
arch_name: LinkNet
encoder_name: mobileone_s4
encoder_weights: imagenet
vv2rgb_name: dB
model_version: staged
hparams:
  -
    image_size: 128
    learning_rate: 0.1
    max_epochs: 1000
    batch_size: 16
    accumulate_grad_batches: 1
  -
    image_size: 320
    learning_rate: 0.01
    max_epochs: 500
    batch_size: 8
    accumulate_grad_batches: 1
  -
    image_size: 640
    learning_rate: 0.001
    max_epochs: 200
    batch_size: 4
    accumulate_grad_batches: 1