data_version: S1
arch_name: DeepLabV3
encoder_name: timm-mobilenetv3_small_100
encoder_weights: imagenet
vv2rgb_name: dB
model_version: default
hparams:
  -
    image_size: 640
    learning_rate: 0.001
    max_epochs: 200
    batch_size: 12
    accumulate_grad_batches: 1